highlighter: pygments
safe: true
lsi: false

# Site settings
title: Nikos Daniilidis
email: nikos.daniilidis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about science, technology, society, and everything in-between.

baseurl: "/altblog" 
url: "http://nikosdaniilidis/github.io/altblog"

twitter_username: ndaniilidis
github_username:  nikosdaniilidis
linked_in: https://www.linkedin.com/in/ndaniilidis

# Build settings
markdown: kramdown

exclude: ['CNAME', 'README.md']
